import type { Metadata } from "next";
import "./globals.css";
import LayoutWrapper from "./components/layout/LayoutWrapper/LayoutWrapper";
import ApolloProviderClient from "./providers/ApolloProviderClient";
import { Prompt } from "next/font/google";
import SchemaScript from "./components/SEO/SchemaScript";
import { organizationSchema } from "./components/SEO/seoSchemas";

export const metadata: Metadata = {
  title: "Fullway",
  description: "Generated by create next app",
};

const prompt = Prompt({
  subsets: ["latin"],
  weight: ["300","400", "500", "600", "700","800","900"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    
     <head>
       <SchemaScript id={"organization-schema"} schema={organizationSchema}/>
      </head>

      <body className={prompt.className}>
        <ApolloProviderClient>
          <LayoutWrapper>{children}</LayoutWrapper>
        </ApolloProviderClient>
      </body>
    </html>
  );
}
